### PR TITLE
Add certificate verification

### PR DESCRIPTION
**Pull request by modille**
See https://urllib3.readthedocs.io/en/latest/user-guide.html#certificate-verification

Fixes https://github.com/zchee/deoplete-docker/issues/1

### CODE REVIEW

**Comment by szymonmaszke** [comment]
Please merge? It's unusable at it's current state...

**Comment by joaosa** [comment]
@zchee merging this would be amazing

**Comment by zchee** [comment]
forgot mention. sorry.
LGTM! merged.

**Comment by joaosa** [comment]
Just a note in case anyway googles this:

Installing `certifi` is required, so if you're using [vim-plug](https://github.com/junegunn/vim-plug), you can simply do this: `Plug 'zchee/deoplete-docker', { 'do': 'pip install certifi' }`.

**Comment by modille** [comment]
Ooh, @joaosa maybe an even better way would be to follow the pattern this plugin uses for its `urllib3` dependency?

Specifically, I think it's just:

- [ ] Add https://github.com/certifi/python-certifi as a submodule
- [ ] Load `certifi` similar to how this plugin loads `urllib3` here: https://github.com/zchee/deoplete-docker/blob/20873fa1921395752b34da812c067f8ed82c6e57/rplugin/python3/deoplete/sources/docker.py#L10

**Comment by zchee** [comment]
@modille 
> Add certifi/python-certifi as a submodule
> Load certifi similar to how this plugin loads urllib3 here:

Correct! could you send pull request if you have time?

**Pull request merged**
